### PR TITLE
Update for CI

### PR DESCRIPTION
**Pull request by p-galligan**
Updates Readme and Travis file for CI performance.

### CODE REVIEW

**Comment by p-galligan** [comment]
@helrond or @bonniegee I'm a little confused about what I'm doing wrong for the Branch build here. I can tell why it's failing based on the travis file, but I'm not quite sure how to fix it, or where I'm going wrong.

Thoughts?

**Comment by helrond** [comment]
Well the short answer is that there is not a $DJANGO_PORT variable available on the branch. If you look at the settings you'll see that there is a variable for the `base` and `development` branches but not other branches.

I believe @bonniegee was in the process of aligning ports/Apache configs on development and production servers. Once that is done we can just target a single port. Otherwise your option is to set a global variable in the Travis config (For something _other_ than DJANGO_PORT so we don't create deployment issues) and use that variable instead.

**Comment by p-galligan** [comment]
> Well the short answer is that there is not a $DJANGO_PORT variable available on the branch. If you look at the settings you'll see that there is a variable for the `base` and `development` branches but not other branches.

Ahhhh, I follow you. I didn't think of that when setting up the settings in Travis.

> I believe @bonniegee was in the process of aligning ports/Apache configs on development and production servers. Once that is done we can just target a single port. Otherwise your option is to set a global variable in the Travis config (For something _other_ than DJANGO_PORT so we don't create deployment issues) and use that variable instead.

Is there an approach we'd prefer here?

**Comment by helrond** [comment]
I would prefer to get ports aligned so we don't have variables we have to untangle in deployment later.

**Comment by bonniegee** [comment]
On both dev and prod, the port is 8011. (All microservice ports should be aligned on dev and production now.)

**Review by helrond — APPROVED** [review]

**Review by bonniegee — APPROVED** [review]

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
