### PR TITLE
Returns exceptions with meaningful messages

### LINKED ISSUE #10: Add logging for BagDiscover routine
Figure out what is logged--and how error handling happens--when bags fail validation.

### PR DESCRIPTION
**Pull request by helrond**
Raises exceptions (rather than just printing out messages). Fixes #10 

@bonniegee I don't really have test coverage for this - the views part of it should be tested in Asterism, but if we wanted to we could probably mock exceptions when we are testing methods. LMK how you feel about that.

### CODE REVIEW

**Comment by bonniegee** [comment]
It looks like tests are failing when a bag is invalid. I think this is where I got stuck when I attempted to tackle this issue a few weeks back. (I'm not sure if this is an issue with the tests?)

**Comment by helrond** [comment]
@bonniegee This is an issue with the fixtures/test logic. The logic before just printed an error, so now our tests need to assert that an exception is thrown. I'll work on this some more.

**Review by bonniegee — APPROVED** [review]
This looks good and makes sense to me. I looked a bit into TypeError, but could you explain why you used that instead of a generic Exception for bag errors?

**Comment by helrond** [comment]
There's not a great reason other than a desire to start to disambiguate the exceptions a bit. We *could* then catch `TypeError`s in the `run` method and do something different with them, like return a different message or perform different cleanup actions.

**Pull request merged**
